### ISSUE TITLE
 FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Tros-t** [JdeRobot/PyOnArduino#26]
Hi I opened this issue to tell you devs about a problem and to thank you, months back I thought I couldn't do my mbot code with python3 but now this lib made everything easy. 

I downloaded the Lib and created a file in the older named test.py and then copy pasted the led test code just to test then on my terminal in vs code I ran py .\translator\Translator.py test.py mbot. everythin was good but at last there was an error.

The Error:

`Traceback (most recent call last):
  File ".\translator\Translator.py", line 711, in <module>
    call(['make'])
  File "C:\Python37\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Kindly help me, I saw your yt and made sure to sub on it.
This is so wunnerfull.

**Comment by Tros-t** [comment]
The full error:
`ARGS: 3
FILENAME: test.py
ROBOT: mbot
NODE generic: <class '_ast.Module'>
NODE generic: <class '_ast.Import'>
NODE generic: <class '_ast.alias'>
NODE generic: <class '_ast.ImportFrom'>
NODE generic: <class '_ast.alias'>
Function Definition: loop
NODE arguments: <class '_ast.arguments'>
NODE arguments: []
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
Attribute: <_ast.Name object at 0x0000019379076FC8><_ast.Load object at 0x0000019378C36548>setLeds
NODE Name: <class '_ast.Name'> hd
NODE Load: <class '_ast.Load'>
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 1
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 2
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 3
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 4
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
NODE Name: <class '_ast.Name'> sleep
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
Attribute: <_ast.Name object at 0x000001937907A308><_ast.Load object at 0x0000019378C36548>setLeds
NODE Name: <class '_ast.Name'> hd
NODE Load: <class '_ast.Load'>
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 1
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 2
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 3
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 4
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
NODE Name: <class '_ast.Name'> sleep
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
Attribute: <_ast.Name object at 0x000001937907A608><_ast.Load object at 0x0000019378C36548>setLeds
NODE Name: <class '_ast.Name'> hd
NODE Load: <class '_ast.Load'>
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 1
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 2
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 3
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 4
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
NODE Name: <class '_ast.Name'> sleep
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
Attribute: <_ast.Name object at 0x000001937907A908><_ast.Load object at 0x0000019378C36548>setLeds
NODE Name: <class '_ast.Name'> hd
NODE Load: <class '_ast.Load'>
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 1
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 2
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 3
NODE Num: <class '_ast.Num'>
CALL_INDEX_NUM 4
PARENTHESES 0
NODE Expr: <class '_ast.Expr'>
NODE Call: <class '_ast.Call'>
NODE Name: <class '_ast.Name'> sleep
NODE Load: <class '_ast.Load'>
NODE Num: <class '_ast.Num'>
PARENTHESES 0
Windows
Traceback (most recent call last):
  File ".\translator\Translator.py", line 711, in <module>
    call(['make'])
  File "C:\Python37\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by Tros-t** [comment]
Why no reply

Pls reply

**Comment by jmplaza** [comment]
Hi @Saad-py ,

this repo has no longer an active support. It is provided "as is", sorry for the inconveniences.

**Comment by Tros-t** [comment]
OMG Why, This is the only thing I wanted, I checked out his yt and commented but no reply and here I thought I can get help.
I am a 12 Year Old, Right now my dream is to control my arduino uno mbot with python

**Comment by jmplaza** [comment]
Hi @Saad-py , we are a nonprofit organization and currently we don't have any developer to maintain that project.

**Comment by Tros-t** [comment]
Thanks @jmplaza for the reply, I don't care if you take a week or a month to solve my error but kindly just help me out
